FROM centos:8.3.2011
RUN curl  -sL https://rpm.nodesource.com/setup_14.x | bash - \    
    && dnf install make \
        gcc-c++ \
        vim \
        nano \
        nodejs -y
COPY react_forum_frontend/ ./react_forum_frontend
WORKDIR /react_forum_frontend
RUN CHOKIDAR_USEPOLLING=true && npm install -g nodemon && npm install
       
